/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedTrainerRouteImport } from './routes/_authed/trainer'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthedTrainerPlayersRouteImport } from './routes/_authed/trainer/players'
import { Route as AuthedTrainerPortalRouteImport } from './routes/_authed/trainer/portal'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users.index'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed/admin/users.$userId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrainerRoute = AuthedTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AuthedRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTrainerPlayersRoute = AuthedTrainerPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthedTrainerRoute,
} as any)
const AuthedTrainerPortalRoute = AuthedTrainerPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthedTrainerRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/trainer': typeof AuthedTrainerRouteWithChildren
  '/join/$code': typeof JoinCodeRoute
  '/trainer/players': typeof AuthedTrainerPlayersRoute
  '/trainer/portal': typeof AuthedTrainerPortalRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/trainer': typeof AuthedTrainerRouteWithChildren
  '/join/$code': typeof JoinCodeRoute
  '/': typeof AuthedIndexRoute
  '/trainer/players': typeof AuthedTrainerPlayersRoute
  '/trainer/portal': typeof AuthedTrainerPortalRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/trainer': typeof AuthedTrainerRouteWithChildren
  '/join/$code': typeof JoinCodeRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/trainer/players': typeof AuthedTrainerPlayersRoute
  '/_authed/trainer/portal': typeof AuthedTrainerPortalRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin'
    | '/profile'
    | '/trainer'
    | '/join/$code'
    | '/trainer/players'
    | '/trainer/portal'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/set-password'
    | '/admin'
    | '/profile'
    | '/trainer'
    | '/join/$code'
    | '/'
    | '/trainer/players'
    | '/trainer/portal'
    | '/admin/users/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/set-password'
    | '/_authed/admin'
    | '/_authed/profile'
    | '/_authed/trainer'
    | '/join/$code'
    | '/_authed/'
    | '/_authed/trainer/players'
    | '/_authed/trainer/portal'
    | '/_authed/admin/users/$userId'
    | '/_authed/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trainer': {
      id: '/_authed/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof AuthedTrainerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/trainer/players': {
      id: '/_authed/trainer/players'
      path: '/players'
      fullPath: '/trainer/players'
      preLoaderRoute: typeof AuthedTrainerPlayersRouteImport
      parentRoute: typeof AuthedTrainerRoute
    }
    '/_authed/trainer/portal': {
      id: '/_authed/trainer/portal'
      path: '/portal'
      fullPath: '/trainer/portal'
      preLoaderRoute: typeof AuthedTrainerPortalRouteImport
      parentRoute: typeof AuthedTrainerRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedTrainerRouteChildren {
  AuthedTrainerPlayersRoute: typeof AuthedTrainerPlayersRoute
  AuthedTrainerPortalRoute: typeof AuthedTrainerPortalRoute
}

const AuthedTrainerRouteChildren: AuthedTrainerRouteChildren = {
  AuthedTrainerPlayersRoute: AuthedTrainerPlayersRoute,
  AuthedTrainerPortalRoute: AuthedTrainerPortalRoute,
}

const AuthedTrainerRouteWithChildren = AuthedTrainerRoute._addFileChildren(
  AuthedTrainerRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedTrainerRoute: typeof AuthedTrainerRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedTrainerRoute: AuthedTrainerRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
